
package knowyourcountry.abs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ABS.Stat_x0020_SDMX_x0020_web_x0020_serviceSoap", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ABSStatX0020SDMXX0020WebX0020ServiceSoap {


    /**
     * Use this method to retrieve the Data Structure Definitions (as well as Code lists and Concepts) from an .Stat dataset. <br>Note: As the requested input parameter is an xml document, you can not try the method using this webservice presentation page. <br><br>Input: SDMX QueryMessage (in SDMX-ML format)<br>Output: SDMX StructureMessage (in SDMX-ML format)
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetDataStructureDefinitionResponse.GetDataStructureDefinitionResult
     */
    @WebMethod(operationName = "GetDataStructureDefinition", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetDataStructureDefinition")
    @WebResult(name = "GetDataStructureDefinitionResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetDataStructureDefinition", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDataStructureDefinition")
    @ResponseWrapper(localName = "GetDataStructureDefinitionResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDataStructureDefinitionResponse")
    public knowyourcountry.abs.GetDataStructureDefinitionResponse.GetDataStructureDefinitionResult getDataStructureDefinition(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetDataStructureDefinition.QueryMessage queryMessage);

    /**
     * Use this method to retrieve data in Generic format from an .Stat dataset. <br>Note: As the requested input parameter is an xml document, you can not try the method using this webservice presentation page. <br><br>Input: SDMX QueryMessage (in SDMX-ML format)<br>Output: SDMX GenericDataMessage (in SDMX-ML format)Our new SDMX web service version implements Streaming, and can therefore not set the 'Truncated' element in the response message. We are thus unable to take the 'defaultLimit' attribute in the Query message into account. To avoid errors, either implement streaming also at your (client) side to allow for greater-sized results or restrict the selection in the query message according to your limitation. In any case, please don't use the 'defaultLimit' attribute in the Query message.
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetGenericDataResponse.GetGenericDataResult
     */
    @WebMethod(operationName = "GetGenericData", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetGenericData")
    @WebResult(name = "GetGenericDataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetGenericData", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetGenericData")
    @ResponseWrapper(localName = "GetGenericDataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetGenericDataResponse")
    public knowyourcountry.abs.GetGenericDataResponse.GetGenericDataResult getGenericData(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetGenericData.QueryMessage queryMessage);

    /**
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetCompactDataResponse.GetCompactDataResult
     */
    @WebMethod(operationName = "GetCompactData", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetCompactData")
    @WebResult(name = "GetCompactDataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetCompactData", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetCompactData")
    @ResponseWrapper(localName = "GetCompactDataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetCompactDataResponse")
    public knowyourcountry.abs.GetCompactDataResponse.GetCompactDataResult getCompactData(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetCompactData.QueryMessage queryMessage);

    /**
     * Use this method to retrieve a range of metadata in a dataset.<br><br>- <a href="Documentation/QueryCoordinatesMD.xml">Sample input</a><br>- <a href="Documentation/CoordinatesMetadata.xml">Sample output</a><br>- <a href="Documentation/GetMetadata.txt">Usage example (C# code)</a><br/><br/><hr/>
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetMetadataResponse.GetMetadataResult
     */
    @WebMethod(operationName = "GetMetadata", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetMetadata")
    @WebResult(name = "GetMetadataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetMetadata", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetMetadata")
    @ResponseWrapper(localName = "GetMetadataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetMetadataResponse")
    public knowyourcountry.abs.GetMetadataResponse.GetMetadataResult getMetadata(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetMetadata.QueryMessage queryMessage);

    /**
     * Use this method to retrieve the metadata associated with a dataset.<br><br>- <a href="Documentation/QueryDatasetMD.xml">Sample input</a><br>- <a href="Documentation/DatasetMetadata.xml">Sample output</a><br>- <a href="Documentation/GetDatasetMetadata.txt">Usage example (C# code)</a><br/><br/><hr/>
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetDatasetMetadataResponse.GetDatasetMetadataResult
     */
    @WebMethod(operationName = "GetDatasetMetadata", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetDatasetMetadata")
    @WebResult(name = "GetDatasetMetadataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetDatasetMetadata", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDatasetMetadata")
    @ResponseWrapper(localName = "GetDatasetMetadataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDatasetMetadataResponse")
    public knowyourcountry.abs.GetDatasetMetadataResponse.GetDatasetMetadataResult getDatasetMetadata(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetDatasetMetadata.QueryMessage queryMessage);

    /**
     * Use this method to retrieve the metadata associated with a dimension in a dataset.<br><br>- <a href="Documentation/QueryDimensionMD.xml">Sample input</a><br>- <a href="Documentation/DimensionMetadata.xml">Sample output</a><br>- <a href="Documentation/GetDimensionMetadata.txt">Usage example (C# code)</a><br/><br/><hr/>
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetDimensionMetadataResponse.GetDimensionMetadataResult
     */
    @WebMethod(operationName = "GetDimensionMetadata", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetDimensionMetadata")
    @WebResult(name = "GetDimensionMetadataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetDimensionMetadata", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDimensionMetadata")
    @ResponseWrapper(localName = "GetDimensionMetadataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDimensionMetadataResponse")
    public knowyourcountry.abs.GetDimensionMetadataResponse.GetDimensionMetadataResult getDimensionMetadata(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetDimensionMetadata.QueryMessage queryMessage);

    /**
     * Use this method to retrieve the metadata associated with a member of a dimension in a dataset.<br><br>- <a href="Documentation/QueryDimensionMemberMD.xml">Sample input</a><br>- <a href="Documentation/DimensionMemberMetadata.xml">Sample output</a><br>- <a href="Documentation/GetDimensionMemberMetadata.txt">Usage example (C# code)</a><br/><br/><hr/>
     * 
     * @param queryMessage
     * @return
     *     returns knowyourcountry.abs.GetDimensionMemberMetadataResponse.GetDimensionMemberMetadataResult
     */
    @WebMethod(operationName = "GetDimensionMemberMetadata", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetDimensionMemberMetadata")
    @WebResult(name = "GetDimensionMemberMetadataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetDimensionMemberMetadata", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDimensionMemberMetadata")
    @ResponseWrapper(localName = "GetDimensionMemberMetadataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetDimensionMemberMetadataResponse")
    public knowyourcountry.abs.GetDimensionMemberMetadataResponse.GetDimensionMemberMetadataResult getDimensionMemberMetadata(
        @WebParam(name = "QueryMessage", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetDimensionMemberMetadata.QueryMessage queryMessage);

    /**
     * Use this method to retrieve all strucural informations about a given dataset.<br><br>- <a href="Documentation/QueryMSD.xml">Sample input</a><br>- <a href="Documentation/MSD.xml">Sample output</a><br>- <a href="Documentation/GetDatasetStructure.txt">Usage example (C# code)</a><br/><br/><hr/>
     * 
     * @param xmlQuery
     * @return
     *     returns knowyourcountry.abs.GetMetadataStructureResponse.GetMetadataStructureResult
     */
    @WebMethod(operationName = "GetMetadataStructure", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetMetadataStructure")
    @WebResult(name = "GetMetadataStructureResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetMetadataStructure", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetMetadataStructure")
    @ResponseWrapper(localName = "GetMetadataStructureResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetMetadataStructureResponse")
    public knowyourcountry.abs.GetMetadataStructureResponse.GetMetadataStructureResult getMetadataStructure(
        @WebParam(name = "XmlQuery", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetMetadataStructure.XmlQuery xmlQuery);

    /**
     * 
     * @param xmlQuery
     * @return
     *     returns knowyourcountry.abs.GetReferenceMetadataResponse.GetReferenceMetadataResult
     */
    @WebMethod(operationName = "GetReferenceMetadata", action = "http://stats.oecd.org/OECDStatWS/SDMX/GetReferenceMetadata")
    @WebResult(name = "GetReferenceMetadataResult", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
    @RequestWrapper(localName = "GetReferenceMetadata", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetReferenceMetadata")
    @ResponseWrapper(localName = "GetReferenceMetadataResponse", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/", className = "knowyourcountry.abs.GetReferenceMetadataResponse")
    public knowyourcountry.abs.GetReferenceMetadataResponse.GetReferenceMetadataResult getReferenceMetadata(
        @WebParam(name = "XmlQuery", targetNamespace = "http://stats.oecd.org/OECDStatWS/SDMX/")
        knowyourcountry.abs.GetReferenceMetadata.XmlQuery xmlQuery);

}
